  version: '3.8'

  services:
    api:
      build: .
      image: employee-api
      container_name: spring_app
      depends_on:
        - db
      ports:
        - "8080:8080"
      environment:
        SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/EmployeeDB
        SPRING_DATASOURCE_USERNAME: postgres
        SPRING_DATASOURCE_PASSWORD: Farikooo05
        SPRING_JPA_HIBERNATE_DDL_AUTO: update

    db:
      image: postgres:15
      container_name: postgres_db
      environment:
        POSTGRES_DB: EmployeeDB
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: Farikooo05
      ports:
        - "5432:5432"
      volumes:
        - pg_data:/var/lib/postgresql/data

  volumes:
    pg_data:
